<?php
/*
* Copyright (c) 2014-2015 SugarCRM Inc.  This product is licensed by SugarCRM
* pursuant to the terms of the End User License Agreement available at
* http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/10_Marketo/
*/

$dictionary["ext_soap_marketo"] = array(
    'comment' => 'vardefs for marketo connector',
    'fields' =>
        array(
            'address' =>
                array(
                    'name' => 'address',
                    'marketo' => 'Address',
                    'vname' => 'LBL_ADDRESS',
                    'type' => 'text',
                    'displayName' => 'Address',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 2000,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'annualrevenue' =>
                array(
                    'name' => 'annualrevenue',
                    'marketo' => 'AnnualRevenue',
                    'vname' => 'LBL_ANNUALREVENUE',
                    'type' => 'currency',
                    'displayName' => 'Annual Revenue',
                    'description' => null,
                    'sourceObject' => 'Company',
                    'size' => null,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'anonymousip' =>
                array(
                    'name' => 'anonymousip',
                    'marketo' => 'AnonymousIP',
                    'vname' => 'LBL_ANONYMOUSIP',
                    'type' => 'varchar',
                    'displayName' => 'Anonymous IP',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => true,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-12-13T05:03:12-06:00',
                ),
            'billingcity' =>
                array(
                    'name' => 'billingcity',
                    'marketo' => 'BillingCity',
                    'vname' => 'LBL_BILLINGCITY',
                    'type' => 'varchar',
                    'displayName' => 'Billing City',
                    'description' => null,
                    'sourceObject' => 'Company',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'billingcountry' =>
                array(
                    'name' => 'billingcountry',
                    'marketo' => 'BillingCountry',
                    'vname' => 'LBL_BILLINGCOUNTRY',
                    'type' => 'varchar',
                    'displayName' => 'Billing Country',
                    'description' => null,
                    'sourceObject' => 'Company',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'billingpostalcode' =>
                array(
                    'name' => 'billingpostalcode',
                    'marketo' => 'BillingPostalCode',
                    'vname' => 'LBL_BILLINGPOSTALCODE',
                    'type' => 'varchar',
                    'displayName' => 'Billing Postal Code',
                    'description' => null,
                    'sourceObject' => 'Company',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'billingstate' =>
                array(
                    'name' => 'billingstate',
                    'marketo' => 'BillingState',
                    'vname' => 'LBL_BILLINGSTATE',
                    'type' => 'varchar',
                    'displayName' => 'Billing State',
                    'description' => null,
                    'sourceObject' => 'Company',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'billingstreet' =>
                array(
                    'name' => 'billingstreet',
                    'marketo' => 'BillingStreet',
                    'vname' => 'LBL_BILLINGSTREET',
                    'type' => 'text',
                    'displayName' => 'Billing Address',
                    'description' => null,
                    'sourceObject' => 'Company',
                    'size' => 2000,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'city' =>
                array(
                    'name' => 'city',
                    'marketo' => 'City',
                    'vname' => 'LBL_CITY',
                    'type' => 'varchar',
                    'displayName' => 'City',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'company' =>
                array(
                    'name' => 'company',
                    'marketo' => 'Company',
                    'vname' => 'LBL_COMPANY',
                    'type' => 'varchar',
                    'displayName' => 'Company Name',
                    'description' => null,
                    'sourceObject' => 'Company',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'country' =>
                array(
                    'name' => 'country',
                    'marketo' => 'Country',
                    'vname' => 'LBL_COUNTRY',
                    'type' => 'varchar',
                    'displayName' => 'Country',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'dateofbirth' =>
                array(
                    'name' => 'dateofbirth',
                    'marketo' => 'DateofBirth',
                    'vname' => 'LBL_DATEOFBIRTH',
                    'type' => 'date',
                    'displayName' => 'Date of Birth',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => null,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'department' =>
                array(
                    'name' => 'department',
                    'marketo' => 'Department',
                    'vname' => 'LBL_DEPARTMENT',
                    'type' => 'varchar',
                    'displayName' => 'Department',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:46-05:00',
                ),
            'donotcall' =>
                array(
                    'name' => 'donotcall',
                    'marketo' => 'DoNotCall',
                    'vname' => 'LBL_DONOTCALL',
                    'type' => 'boolean',
                    'displayName' => 'Do Not Call',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => null,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'donotcallreason' =>
                array(
                    'name' => 'donotcallreason',
                    'marketo' => 'DoNotCallReason',
                    'vname' => 'LBL_DONOTCALLREASON',
                    'type' => 'varchar',
                    'displayName' => 'Do Not Call Reason',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 2000,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'email' =>
                array(
                    'name' => 'email',
                    'marketo' => 'Email',
                    'vname' => 'LBL_EMAIL',
                    'type' => 'email',
                    'displayName' => 'Email Address',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => false,
                    'dynamicFieldRef' => null,
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'fax' =>
                array(
                    'name' => 'fax',
                    'marketo' => 'Fax',
                    'vname' => 'LBL_FAX',
                    'type' => 'phone',
                    'displayName' => 'Fax Number',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'firstname' =>
                array(
                    'name' => 'firstname',
                    'marketo' => 'FirstName',
                    'vname' => 'LBL_FIRSTNAME',
                    'type' => 'varchar',
                    'displayName' => 'First Name',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'industry' =>
                array(
                    'name' => 'industry',
                    'marketo' => 'Industry',
                    'vname' => 'LBL_INDUSTRY',
                    'type' => 'varchar',
                    'displayName' => 'Industry',
                    'description' => null,
                    'sourceObject' => 'Company',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'inferredcompany' =>
                array(
                    'name' => 'inferredcompany',
                    'marketo' => 'InferredCompany',
                    'vname' => 'LBL_INFERREDCOMPANY',
                    'type' => 'varchar',
                    'displayName' => 'Inferred Company',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'inferredcountry' =>
                array(
                    'name' => 'inferredcountry',
                    'marketo' => 'InferredCountry',
                    'vname' => 'LBL_INFERREDCOUNTRY',
                    'type' => 'varchar',
                    'displayName' => 'Inferred Country',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'lastname' =>
                array(
                    'name' => 'lastname',
                    'marketo' => 'LastName',
                    'vname' => 'LBL_LASTNAME',
                    'type' => 'varchar',
                    'displayName' => 'Last Name',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'leadrole' =>
                array(
                    'name' => 'leadrole',
                    'marketo' => 'LeadRole',
                    'vname' => 'LBL_LEADROLE',
                    'type' => 'varchar',
                    'displayName' => 'Role',
                    'description' => null,
                    'sourceObject' => 'LeadInterest',
                    'size' => 50,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'leadscore' =>
                array(
                    'name' => 'leadscore',
                    'marketo' => 'LeadScore',
                    'vname' => 'LBL_LEADSCORE',
                    'type' => 'int',
                    'displayName' => 'Lead Score',
                    'description' => null,
                    'sourceObject' => 'LeadInterest',
                    'size' => null,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'leadsource' =>
                array(
                    'name' => 'leadsource',
                    'marketo' => 'LeadSource',
                    'vname' => 'LBL_LEADSOURCE',
                    'type' => 'varchar',
                    'displayName' => 'Lead Source',
                    'description' => null,
                    'sourceObject' => 'LeadInterest',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'leadstatus' =>
                array(
                    'name' => 'leadstatus',
                    'marketo' => 'LeadStatus',
                    'vname' => 'LBL_LEADSTATUS',
                    'type' => 'varchar',
                    'displayName' => 'Lead Status',
                    'description' => null,
                    'sourceObject' => 'LeadInterest',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'mainphone' =>
                array(
                    'name' => 'mainphone',
                    'marketo' => 'MainPhone',
                    'vname' => 'LBL_MAINPHONE',
                    'type' => 'varchar',
                    'displayName' => 'Main Phone',
                    'description' => null,
                    'sourceObject' => 'Company',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'middlename' =>
                array(
                    'name' => 'middlename',
                    'marketo' => 'MiddleName',
                    'vname' => 'LBL_MIDDLENAME',
                    'type' => 'varchar',
                    'displayName' => 'Middle Name',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'mobilephone' =>
                array(
                    'name' => 'mobilephone',
                    'marketo' => 'MobilePhone',
                    'vname' => 'LBL_MOBILEPHONE',
                    'type' => 'phone',
                    'displayName' => 'Mobile Phone Number',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'numberofemployees' =>
                array(
                    'name' => 'numberofemployees',
                    'marketo' => 'NumberOfEmployees',
                    'vname' => 'LBL_NUMBEROFEMPLOYEES',
                    'type' => 'int',
                    'displayName' => 'Num Employees',
                    'description' => null,
                    'sourceObject' => 'Company',
                    'size' => null,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'phone' =>
                array(
                    'name' => 'phone',
                    'marketo' => 'Phone',
                    'vname' => 'LBL_PHONE',
                    'type' => 'phone',
                    'displayName' => 'Phone Number',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'postalcode' =>
                array(
                    'name' => 'postalcode',
                    'marketo' => 'PostalCode',
                    'vname' => 'LBL_POSTALCODE',
                    'type' => 'varchar',
                    'displayName' => 'Postal Code',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'rating' =>
                array(
                    'name' => 'rating',
                    'marketo' => 'Rating',
                    'vname' => 'LBL_RATING',
                    'type' => 'varchar',
                    'displayName' => 'Lead Rating',
                    'description' => null,
                    'sourceObject' => 'LeadInterest',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'salutation' =>
                array(
                    'name' => 'salutation',
                    'marketo' => 'Salutation',
                    'vname' => 'LBL_SALUTATION',
                    'type' => 'varchar',
                    'displayName' => 'Salutation',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'siccode' =>
                array(
                    'name' => 'siccode',
                    'marketo' => 'SICCode',
                    'vname' => 'LBL_SICCODE',
                    'type' => 'varchar',
                    'displayName' => 'SIC Code',
                    'description' => null,
                    'sourceObject' => 'Company',
                    'size' => 40,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'site' =>
                array(
                    'name' => 'site',
                    'marketo' => 'Site',
                    'vname' => 'LBL_SITE',
                    'type' => 'varchar',
                    'displayName' => 'Site',
                    'description' => null,
                    'sourceObject' => 'Company',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'state' =>
                array(
                    'name' => 'state',
                    'marketo' => 'State',
                    'vname' => 'LBL_STATE',
                    'type' => 'varchar',
                    'displayName' => 'State',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'title' =>
                array(
                    'name' => 'title',
                    'marketo' => 'Title',
                    'vname' => 'LBL_TITLE',
                    'type' => 'varchar',
                    'displayName' => 'Job Title',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'unsubscribed' =>
                array(
                    'name' => 'unsubscribed',
                    'marketo' => 'Unsubscribed',
                    'vname' => 'LBL_UNSUBSCRIBED',
                    'type' => 'boolean',
                    'displayName' => 'Unsubscribed',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => null,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'unsubscribedreason' =>
                array(
                    'name' => 'unsubscribedreason',
                    'marketo' => 'UnsubscribedReason',
                    'vname' => 'LBL_UNSUBSCRIBEDREASON',
                    'type' => 'varchar',
                    'displayName' => 'Unsubscribed Reason',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 2000,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'emailinvalid' =>
                array(
                    'name' => 'emailinvalid',
                    'marketo' => 'EmailInvalid',
                    'vname' => 'LBL_EMAILINVALID',
                    'type' => 'boolean',
                    'displayName' => 'Email Invalid',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => null,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2015-11-20T11:35:33-06:00',
                ),
            'website' =>
                array(
                    'name' => 'website',
                    'marketo' => 'Website',
                    'vname' => 'LBL_WEBSITE',
                    'type' => 'url',
                    'displayName' => 'Website',
                    'description' => null,
                    'sourceObject' => 'Company',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2013-04-15T15:15:45-05:00',
                ),
            'sugarcrm_id' =>
                array(
                    'name' => 'sugarcrm_id',
                    'marketo' => 'sugarcrm_id',
                    'vname' => 'LBL_SUGARCRM_ID',
                    'type' => 'varchar',
                    'displayName' => 'SugarCRM Record ID',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => true,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2014-01-31T13:33:20-06:00',
                ),
            'sugarcrm_owner_email' =>
                array(
                    'name' => 'sugarcrm_owner_email',
                    'marketo' => 'sugarcrm_owner_email',
                    'vname' => 'LBL_SUGARCRM_OWNER_EMAIL',
                    'type' => 'email',
                    'displayName' => 'SugarCRM Owner Email Address',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => true,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2014-01-31T13:30:16-06:00',
                ),
            'sugarcrm_owner_first_name' =>
                array(
                    'name' => 'sugarcrm_owner_first_name',
                    'marketo' => 'sugarcrm_owner_first_name',
                    'vname' => 'LBL_SUGARCRM_OWNER_FIRST_NAME',
                    'type' => 'varchar',
                    'displayName' => 'SugarCRM Owner First Name',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => true,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2014-01-31T13:28:50-06:00',
                ),
            'sugarcrm_owner_last_name' =>
                array(
                    'name' => 'sugarcrm_owner_last_name',
                    'marketo' => 'sugarcrm_owner_last_name',
                    'vname' => 'LBL_SUGARCRM_OWNER_LAST_NAME',
                    'type' => 'varchar',
                    'displayName' => 'SugarCRM Owner Last Name',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => true,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2014-01-31T13:29:32-06:00',
                ),
            'sugarcrm_owner_phone' =>
                array(
                    'name' => 'sugarcrm_owner_phone',
                    'marketo' => 'sugarcrm_owner_phone',
                    'vname' => 'LBL_SUGARCRM_OWNER_PHONE',
                    'type' => 'phone',
                    'displayName' => 'SugarCRM Owner Phone',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => true,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2014-01-31T13:29:50-06:00',
                ),
            'sugarcrm_owner_title' =>
                array(
                    'name' => 'sugarcrm_owner_title',
                    'marketo' => 'sugarcrm_owner_title',
                    'vname' => 'LBL_SUGARCRM_OWNER_TITLE',
                    'type' => 'varchar',
                    'displayName' => 'SugarCRM Owner Title',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => true,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2014-01-31T13:30:44-06:00',
                ),
            'sugarcrm_type' =>
                array(
                    'name' => 'sugarcrm_type',
                    'marketo' => 'sugarcrm_type',
                    'vname' => 'LBL_SUGARCRM_TYPE',
                    'type' => 'varchar',
                    'displayName' => 'SugarCRM Type',
                    'description' => null,
                    'sourceObject' => 'Lead',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => true,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'leadAttributeList',
                    'updatedAt' => '2014-01-31T13:31:15-06:00',
                ),
        ),
);
