<?php
/*
* Copyright (c) 2014-2015 SugarCRM Inc.  This product is licensed by SugarCRM
* pursuant to the terms of the End User License Agreement available at
* http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/10_Marketo/
*/

$dictionary["ext_soap_marketo_role"] = array(
    'comment' => 'vardefs for marketo connector',
    'fields' =>
        array(
            'externalcreateddate' =>
                array(
                    'name' => 'externalcreateddate',
                    'marketo' => 'ExternalCreatedDate',
                    'vname' => 'LBL_EXTERNALCREATEDDATE',
                    'type' => 'datetime',
                    'displayName' => 'SFDC Created Date',
                    'description' => null,
                    'sourceObject' => 'OpportunityPersonRole',
                    'size' => null,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => false,
                    'dynamicFieldRef' => null,
                    'updatedAt' => '2013-04-15T15:15:46-05:00',
                ),
            'id' =>
                array(
                    'name' => 'id',
                    'marketo' => 'Id',
                    'vname' => 'LBL_ID',
                    'type' => 'int',
                    'displayName' => 'Id',
                    'description' => null,
                    'sourceObject' => 'OpportunityPersonRole',
                    'size' => null,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => true,
                    'dynamicFieldRef' => 'attributeList',
                    'updatedAt' => '2013-04-15T15:15:46-05:00',
                ),
            'isprimary' =>
                array(
                    'name' => 'isprimary',
                    'marketo' => 'IsPrimary',
                    'vname' => 'LBL_ISPRIMARY',
                    'type' => 'boolean',
                    'displayName' => 'Is Primary',
                    'description' => null,
                    'sourceObject' => 'OpportunityPersonRole',
                    'size' => null,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => false,
                    'dynamicFieldRef' => null,
                    'updatedAt' => '2013-04-15T15:15:46-05:00',
                ),
            'opportunityid' =>
                array(
                    'name' => 'opportunityid',
                    'marketo' => 'OpportunityId',
                    'vname' => 'LBL_OPPORTUNITYID',
                    'type' => 'reference',
                    'displayName' => 'Opportunity Id',
                    'description' => null,
                    'sourceObject' => 'OpportunityPersonRole',
                    'size' => null,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => false,
                    'dynamicFieldRef' => null,
                    'updatedAt' => '2013-04-15T15:15:46-05:00',
                ),
            'personid' =>
                array(
                    'name' => 'personid',
                    'marketo' => 'PersonId',
                    'vname' => 'LBL_PERSONID',
                    'type' => 'reference',
                    'displayName' => 'Contact Id',
                    'description' => null,
                    'sourceObject' => 'OpportunityPersonRole',
                    'size' => null,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => false,
                    'dynamicFieldRef' => null,
                    'updatedAt' => '2013-04-15T15:15:46-05:00',
                ),
            'role' =>
                array(
                    'name' => 'role',
                    'marketo' => 'Role',
                    'vname' => 'LBL_ROLE',
                    'type' => 'varchar',
                    'displayName' => 'Role',
                    'description' => null,
                    'sourceObject' => 'OpportunityPersonRole',
                    'size' => 255,
                    'isReadonly' => false,
                    'isUpdateBlocked' => false,
                    'isName' => null,
                    'isPrimaryKey' => false,
                    'isCustom' => false,
                    'isDynamic' => false,
                    'dynamicFieldRef' => null,
                    'updatedAt' => '2013-04-15T15:15:46-05:00',
                ),
        ),
);
