<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN zzz_lot
 */


class zzz_lot_sugar extends Basic {
    public $new_schema = true;
    public $module_dir = 'zzz_lot';
    public $object_name = 'zzz_lot';
    public $table_name = 'zzz_lot';
    public $importable = true;
    public $team_id;
    public $team_set_id;
    public $team_count;
    public $team_name;
    public $team_link;
    public $team_count_link;
    public $teams;
    public $assigned_user_id;
    public $assigned_user_name;
    public $assigned_user_link;
    public $tag;
    public $tag_link;
    public $id;
    public $name;
    public $date_entered;
    public $date_modified;
    public $modified_user_id;
    public $modified_by_name;
    public $created_by;
    public $created_by_name;
    public $description;
    public $deleted;
    public $created_by_link;
    public $modified_user_link;
    public $activities;
    public $following;
    public $following_link;
    public $my_favorite;
    public $favorite_link;
    public $lot_code;
    public $lot_bumi_lot;
    public $lot_address_street;
    public $lot_address_city;
    public $lot_address_state;
    public $lot_address_postalcode;
    public $lot_address_country;
    public $lot_management_reserve;
    public $lot_booking_remark;
    public $lot_hsd_no;
    public $lot_ptd_no;
    public $lot_unit_measure;
    public $lot_position;
    public $lot_direction;
    public $lot_building_type;
    public $lot_building_design;
    public $lot_block;
    public $lot_level;
    public $lot_view_type;
    public $lot_finishing;
    public $lot_tax_exclude;
    public $lot_handover_date;
    public $lot_status;
    public $lot_bumi_release;
    public $lot_booking_date;
    public $lot_buildup_area;
    public $lot_land_area;
    public $lot_list_price;
    public $lot_total_amt;
    public $lot_est_selling_prc;
    
    /**
     * This is a deprecated method, please start using __construct() as this
     * method will be removed in a future version.
     *
     * @see __construct
     * @deprecated
     */
    public function zzz_lot_sugar(){
        $GLOBALS['log']->deprecated('Calls to zzz_lot::zzz_lot are deprecated.');
        self::__construct();
    }

    public function __construct(){
        parent::__construct();
    }
    
    public function bean_implements($interface){
        switch($interface){
            case 'ACL': return true;
        }
        return false;
    }
    
}